export {
  Permission,
  ROLE_PERMISSIONS,
  ROLE_DESCRIPTIONS,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getRolePermissions,
  canPerformAction,
  getRoleHierarchy,
  isHigherRole,
  getAssignableRoles,
  canChangeRole,
  type AuthorizationResult,
  type UserProjectAccess,
  getUserProjectAccess,
  authorizeUserAction,
  authorizeUserAnyPermission,
  requirePermission,
  canModifyCollaborator,
  canRemoveCollaborator,
  userOwnsResource,
  getUserProjectsWithPermission,
  getUserPermissions,
  canAccessRealtimeCollab,
  CollaboratorRole,
} from "./lib";
