/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as HelppageRouteImport } from './app/helppage'
import { Route as ProtectedRouteImport } from './app/_protected'
import { Route as AuthRouteImport } from './app/_auth'
import { Route as IndexRouteImport } from './app/index'
import { Route as PreviewIdRouteImport } from './app/preview/$id'
import { Route as ApiGettokenRouteImport } from './app/api/gettoken'
import { Route as ApiGenerateCodeRouteImport } from './app/api/generate-code'
import { Route as ApiAnalyticsRouteImport } from './app/api/analytics'
import { Route as ProtectedProfileRouteImport } from './app/_protected/profile'
import { Route as ProtectedNotificationsRouteImport } from './app/_protected/notifications'
import { Route as ProtectedMarketplaceRouteImport } from './app/_protected/marketplace'
import { Route as ProtectedHelpRouteImport } from './app/_protected/help'
import { Route as ProtectedDashboardRouteImport } from './app/_protected/dashboard'
import { Route as ProtectedAnalyticsRouteImport } from './app/_protected/analytics'
import { Route as ProtectedAcceptInvitationRouteImport } from './app/_protected/accept-invitation'
import { Route as AuthSignUpRouteImport } from './app/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './app/_auth/sign-in'
import { Route as ApiNotificationsIndexRouteImport } from './app/api/notifications/index'
import { Route as ProtectedProfileIndexRouteImport } from './app/_protected/profile/index'
import { Route as ProtectedNotificationsIndexRouteImport } from './app/_protected/notifications/index'
import { Route as ProtectedMarketplaceIndexRouteImport } from './app/_protected/marketplace/index'
import { Route as ProtectedDashboardIndexRouteImport } from './app/_protected/dashboard/index'
import { Route as ProtectedAnalyticsIndexRouteImport } from './app/_protected/analytics/index'
import { Route as ApiNotificationsProfileUpdateRouteImport } from './app/api/notifications/profile-update'
import { Route as ProtectedProjectsettingsIdRouteImport } from './app/_protected/projectsettings.$id'
import { Route as ProtectedMarketplaceIdRouteImport } from './app/_protected/marketplace/$id'
import { Route as ProtectedEditorIdRouteImport } from './app/_protected/editor.$id'
import { Route as ProtectedEditorIdIndexRouteImport } from './app/_protected/editor.$id/index'

const HelppageRoute = HelppageRouteImport.update({
  id: '/helppage',
  path: '/helppage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIdRoute = PreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGettokenRoute = ApiGettokenRouteImport.update({
  id: '/api/gettoken',
  path: '/api/gettoken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCodeRoute = ApiGenerateCodeRouteImport.update({
  id: '/api/generate-code',
  path: '/api/generate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsRoute = ProtectedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMarketplaceRoute = ProtectedMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAcceptInvitationRoute =
  ProtectedAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedProfileRoute,
} as any)
const ProtectedNotificationsIndexRoute =
  ProtectedNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedNotificationsRoute,
  } as any)
const ProtectedMarketplaceIndexRoute =
  ProtectedMarketplaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMarketplaceRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedAnalyticsIndexRoute = ProtectedAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAnalyticsRoute,
} as any)
const ApiNotificationsProfileUpdateRoute =
  ApiNotificationsProfileUpdateRouteImport.update({
    id: '/api/notifications/profile-update',
    path: '/api/notifications/profile-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedProjectsettingsIdRoute =
  ProtectedProjectsettingsIdRouteImport.update({
    id: '/projectsettings/$id',
    path: '/projectsettings/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMarketplaceIdRoute = ProtectedMarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtectedMarketplaceRoute,
} as any)
const ProtectedEditorIdRoute = ProtectedEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEditorIdIndexRoute = ProtectedEditorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedEditorIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/helppage': typeof HelppageRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/accept-invitation': typeof ProtectedAcceptInvitationRoute
  '/analytics': typeof ProtectedAnalyticsRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/help': typeof ProtectedHelpRoute
  '/marketplace': typeof ProtectedMarketplaceRouteWithChildren
  '/notifications': typeof ProtectedNotificationsRouteWithChildren
  '/profile': typeof ProtectedProfileRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/generate-code': typeof ApiGenerateCodeRoute
  '/api/gettoken': typeof ApiGettokenRoute
  '/preview/$id': typeof PreviewIdRoute
  '/editor/$id': typeof ProtectedEditorIdRouteWithChildren
  '/marketplace/$id': typeof ProtectedMarketplaceIdRoute
  '/projectsettings/$id': typeof ProtectedProjectsettingsIdRoute
  '/api/notifications/profile-update': typeof ApiNotificationsProfileUpdateRoute
  '/analytics/': typeof ProtectedAnalyticsIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/marketplace/': typeof ProtectedMarketplaceIndexRoute
  '/notifications/': typeof ProtectedNotificationsIndexRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/editor/$id/': typeof ProtectedEditorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/helppage': typeof HelppageRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/accept-invitation': typeof ProtectedAcceptInvitationRoute
  '/help': typeof ProtectedHelpRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/generate-code': typeof ApiGenerateCodeRoute
  '/api/gettoken': typeof ApiGettokenRoute
  '/preview/$id': typeof PreviewIdRoute
  '/marketplace/$id': typeof ProtectedMarketplaceIdRoute
  '/projectsettings/$id': typeof ProtectedProjectsettingsIdRoute
  '/api/notifications/profile-update': typeof ApiNotificationsProfileUpdateRoute
  '/analytics': typeof ProtectedAnalyticsIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/marketplace': typeof ProtectedMarketplaceIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/editor/$id': typeof ProtectedEditorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/helppage': typeof HelppageRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/accept-invitation': typeof ProtectedAcceptInvitationRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/marketplace': typeof ProtectedMarketplaceRouteWithChildren
  '/_protected/notifications': typeof ProtectedNotificationsRouteWithChildren
  '/_protected/profile': typeof ProtectedProfileRouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/generate-code': typeof ApiGenerateCodeRoute
  '/api/gettoken': typeof ApiGettokenRoute
  '/preview/$id': typeof PreviewIdRoute
  '/_protected/editor/$id': typeof ProtectedEditorIdRouteWithChildren
  '/_protected/marketplace/$id': typeof ProtectedMarketplaceIdRoute
  '/_protected/projectsettings/$id': typeof ProtectedProjectsettingsIdRoute
  '/api/notifications/profile-update': typeof ApiNotificationsProfileUpdateRoute
  '/_protected/analytics/': typeof ProtectedAnalyticsIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/marketplace/': typeof ProtectedMarketplaceIndexRoute
  '/_protected/notifications/': typeof ProtectedNotificationsIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/_protected/editor/$id/': typeof ProtectedEditorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/helppage'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation'
    | '/analytics'
    | '/dashboard'
    | '/help'
    | '/marketplace'
    | '/notifications'
    | '/profile'
    | '/api/analytics'
    | '/api/generate-code'
    | '/api/gettoken'
    | '/preview/$id'
    | '/editor/$id'
    | '/marketplace/$id'
    | '/projectsettings/$id'
    | '/api/notifications/profile-update'
    | '/analytics/'
    | '/dashboard/'
    | '/marketplace/'
    | '/notifications/'
    | '/profile/'
    | '/api/notifications/'
    | '/editor/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/helppage'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation'
    | '/help'
    | '/api/analytics'
    | '/api/generate-code'
    | '/api/gettoken'
    | '/preview/$id'
    | '/marketplace/$id'
    | '/projectsettings/$id'
    | '/api/notifications/profile-update'
    | '/analytics'
    | '/dashboard'
    | '/marketplace'
    | '/notifications'
    | '/profile'
    | '/api/notifications'
    | '/editor/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/helppage'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/accept-invitation'
    | '/_protected/analytics'
    | '/_protected/dashboard'
    | '/_protected/help'
    | '/_protected/marketplace'
    | '/_protected/notifications'
    | '/_protected/profile'
    | '/api/analytics'
    | '/api/generate-code'
    | '/api/gettoken'
    | '/preview/$id'
    | '/_protected/editor/$id'
    | '/_protected/marketplace/$id'
    | '/_protected/projectsettings/$id'
    | '/api/notifications/profile-update'
    | '/_protected/analytics/'
    | '/_protected/dashboard/'
    | '/_protected/marketplace/'
    | '/_protected/notifications/'
    | '/_protected/profile/'
    | '/api/notifications/'
    | '/_protected/editor/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  HelppageRoute: typeof HelppageRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiGenerateCodeRoute: typeof ApiGenerateCodeRoute
  ApiGettokenRoute: typeof ApiGettokenRoute
  PreviewIdRoute: typeof PreviewIdRoute
  ApiNotificationsProfileUpdateRoute: typeof ApiNotificationsProfileUpdateRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/helppage': {
      id: '/helppage'
      path: '/helppage'
      fullPath: '/helppage'
      preLoaderRoute: typeof HelppageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$id': {
      id: '/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof PreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gettoken': {
      id: '/api/gettoken'
      path: '/api/gettoken'
      fullPath: '/api/gettoken'
      preLoaderRoute: typeof ApiGettokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-code': {
      id: '/api/generate-code'
      path: '/api/generate-code'
      fullPath: '/api/generate-code'
      preLoaderRoute: typeof ApiGenerateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications': {
      id: '/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/marketplace': {
      id: '/_protected/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof ProtectedMarketplaceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/accept-invitation': {
      id: '/_protected/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof ProtectedAcceptInvitationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedProfileRoute
    }
    '/_protected/notifications/': {
      id: '/_protected/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof ProtectedNotificationsIndexRouteImport
      parentRoute: typeof ProtectedNotificationsRoute
    }
    '/_protected/marketplace/': {
      id: '/_protected/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof ProtectedMarketplaceIndexRouteImport
      parentRoute: typeof ProtectedMarketplaceRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/analytics/': {
      id: '/_protected/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof ProtectedAnalyticsIndexRouteImport
      parentRoute: typeof ProtectedAnalyticsRoute
    }
    '/api/notifications/profile-update': {
      id: '/api/notifications/profile-update'
      path: '/api/notifications/profile-update'
      fullPath: '/api/notifications/profile-update'
      preLoaderRoute: typeof ApiNotificationsProfileUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/projectsettings/$id': {
      id: '/_protected/projectsettings/$id'
      path: '/projectsettings/$id'
      fullPath: '/projectsettings/$id'
      preLoaderRoute: typeof ProtectedProjectsettingsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/marketplace/$id': {
      id: '/_protected/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof ProtectedMarketplaceIdRouteImport
      parentRoute: typeof ProtectedMarketplaceRoute
    }
    '/_protected/editor/$id': {
      id: '/_protected/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof ProtectedEditorIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/editor/$id/': {
      id: '/_protected/editor/$id/'
      path: '/'
      fullPath: '/editor/$id/'
      preLoaderRoute: typeof ProtectedEditorIdIndexRouteImport
      parentRoute: typeof ProtectedEditorIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAnalyticsRouteChildren {
  ProtectedAnalyticsIndexRoute: typeof ProtectedAnalyticsIndexRoute
}

const ProtectedAnalyticsRouteChildren: ProtectedAnalyticsRouteChildren = {
  ProtectedAnalyticsIndexRoute: ProtectedAnalyticsIndexRoute,
}

const ProtectedAnalyticsRouteWithChildren =
  ProtectedAnalyticsRoute._addFileChildren(ProtectedAnalyticsRouteChildren)

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedMarketplaceRouteChildren {
  ProtectedMarketplaceIdRoute: typeof ProtectedMarketplaceIdRoute
  ProtectedMarketplaceIndexRoute: typeof ProtectedMarketplaceIndexRoute
}

const ProtectedMarketplaceRouteChildren: ProtectedMarketplaceRouteChildren = {
  ProtectedMarketplaceIdRoute: ProtectedMarketplaceIdRoute,
  ProtectedMarketplaceIndexRoute: ProtectedMarketplaceIndexRoute,
}

const ProtectedMarketplaceRouteWithChildren =
  ProtectedMarketplaceRoute._addFileChildren(ProtectedMarketplaceRouteChildren)

interface ProtectedNotificationsRouteChildren {
  ProtectedNotificationsIndexRoute: typeof ProtectedNotificationsIndexRoute
}

const ProtectedNotificationsRouteChildren: ProtectedNotificationsRouteChildren =
  {
    ProtectedNotificationsIndexRoute: ProtectedNotificationsIndexRoute,
  }

const ProtectedNotificationsRouteWithChildren =
  ProtectedNotificationsRoute._addFileChildren(
    ProtectedNotificationsRouteChildren,
  )

interface ProtectedProfileRouteChildren {
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedProfileRouteChildren: ProtectedProfileRouteChildren = {
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedProfileRouteWithChildren =
  ProtectedProfileRoute._addFileChildren(ProtectedProfileRouteChildren)

interface ProtectedEditorIdRouteChildren {
  ProtectedEditorIdIndexRoute: typeof ProtectedEditorIdIndexRoute
}

const ProtectedEditorIdRouteChildren: ProtectedEditorIdRouteChildren = {
  ProtectedEditorIdIndexRoute: ProtectedEditorIdIndexRoute,
}

const ProtectedEditorIdRouteWithChildren =
  ProtectedEditorIdRoute._addFileChildren(ProtectedEditorIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAcceptInvitationRoute: typeof ProtectedAcceptInvitationRoute
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedMarketplaceRoute: typeof ProtectedMarketplaceRouteWithChildren
  ProtectedNotificationsRoute: typeof ProtectedNotificationsRouteWithChildren
  ProtectedProfileRoute: typeof ProtectedProfileRouteWithChildren
  ProtectedEditorIdRoute: typeof ProtectedEditorIdRouteWithChildren
  ProtectedProjectsettingsIdRoute: typeof ProtectedProjectsettingsIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAcceptInvitationRoute: ProtectedAcceptInvitationRoute,
  ProtectedAnalyticsRoute: ProtectedAnalyticsRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedMarketplaceRoute: ProtectedMarketplaceRouteWithChildren,
  ProtectedNotificationsRoute: ProtectedNotificationsRouteWithChildren,
  ProtectedProfileRoute: ProtectedProfileRouteWithChildren,
  ProtectedEditorIdRoute: ProtectedEditorIdRouteWithChildren,
  ProtectedProjectsettingsIdRoute: ProtectedProjectsettingsIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  HelppageRoute: HelppageRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiGenerateCodeRoute: ApiGenerateCodeRoute,
  ApiGettokenRoute: ApiGettokenRoute,
  PreviewIdRoute: PreviewIdRoute,
  ApiNotificationsProfileUpdateRoute: ApiNotificationsProfileUpdateRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
